import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";
import localFont from 'next/font/local';

const tajawal = localFont({
  src: './fonts/Tajawal-Regular.ttf',
  variable: '--font-tajawal',
  weight: '100 900',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${tajawal.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <NavBar/>
        {children}
        <Footer />
        </body>
    </html>
  );
}
